### ISSUE TITLE
View full list of who your trust flows to, sorted by most trusted.

### ISSUE THREAD

**Issue by tayler6000** [eigenkarmanetwork/EKN#8]

**Comment by tayler6000** [comment]
@plexish Just to follow up on our discussion in the discord, since it takes about half a second to calculate trust for each user the best way to do this is just to do one ET calc without the loop avoidance.  It won't be perfect, but this gives you a close estimate in a situation where it doesn't matter to much since your network will still be correct.

**Comment by plexish** [comment]
Hm, yeah, no loop avoidance is better than taking a minute to load, and this is the most straightforward way to do it.

**Comment by plexish** [comment]
It would be great to have this displayed on the website too, might want to pull @ChrisRimmer in to make the UI for that. Something like 

![Image](https://user-images.githubusercontent.com/1039691/184727146-c5be4adf-7057-4971-a931-4ed2d0443aa0.png)

**Comment by tayler6000** [comment]
Consolidating into #34
